/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimalsIdRouteImport } from './routes/animals.$id'
import { Route as ApiPublicPredictRiskRouteImport } from './routes/api/public/predict-risk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIdRoute = AnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPredictRiskRoute = ApiPublicPredictRiskRouteImport.update({
  id: '/api/public/predict-risk',
  path: '/api/public/predict-risk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/api/public/predict-risk': typeof ApiPublicPredictRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/api/public/predict-risk': typeof ApiPublicPredictRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/api/public/predict-risk': typeof ApiPublicPredictRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animals/$id' | '/api/public/predict-risk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animals/$id' | '/api/public/predict-risk'
  id: '__root__' | '/' | '/animals/$id' | '/api/public/predict-risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsIdRoute: typeof AnimalsIdRoute
  ApiPublicPredictRiskRoute: typeof ApiPublicPredictRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$id': {
      id: '/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AnimalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/predict-risk': {
      id: '/api/public/predict-risk'
      path: '/api/public/predict-risk'
      fullPath: '/api/public/predict-risk'
      preLoaderRoute: typeof ApiPublicPredictRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsIdRoute: AnimalsIdRoute,
  ApiPublicPredictRiskRoute: ApiPublicPredictRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
